# Generated by Skyramp v1.3.19 on 2026-04-20 17:48:20.461703207 +0000 UTC m=+334.865950629
# Command: skyramp generate contract rest http://localhost:8000/api/v1/features/bulk-evaluate/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output bulk_evaluate_validation_contract_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature_names":["flag-1","flag-2","flag-3","flag-4","flag-5","flag-6","flag-7","flag-8","flag-9","flag-10","flag-11","flag-12","flag-13","flag-14","flag-15","flag-16","flag-17","flag-18","flag-19","flag-20","flag-21","flag-22","flag-23","flag-24","flag-25","flag-26","flag-27","flag-28","flag-29","flag-30","flag-31","flag-32","flag-33","flag-34","flag-35","flag-36","flag-37","flag-38","flag-39","flag-40","flag-41","flag-42","flag-43","flag-44","flag-45","flag-46","flag-47","flag-48","flag-49","flag-50","flag-51","flag-52","flag-53","flag-54","flag-55","flag-56","flag-57","flag-58","flag-59","flag-60","flag-61","flag-62","flag-63","flag-64","flag-65","flag-66","flag-67","flag-68","flag-69","flag-70","flag-71","flag-72","flag-73","flag-74","flag-75","flag-76","flag-77","flag-78","flag-79","flag-80","flag-81","flag-82","flag-83","flag-84","flag-85","flag-86","flag-87","flag-88","flag-89","flag-90","flag-91","flag-92","flag-93","flag-94","flag-95","flag-96","flag-97","flag-98","flag-99","flag-100","flag-101"],"identifier":""} \
# 		--response-status-code 400 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/features/bulk-evaluate/ POST
def test_bulk_evaluate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    bulk_evaluate_POST_request_body = r'''{
        "feature_names": [
            "flag-1",
            "flag-2",
            "flag-3",
            "flag-4",
            "flag-5",
            "flag-6",
            "flag-7",
            "flag-8",
            "flag-9",
            "flag-10",
            "flag-11",
            "flag-12",
            "flag-13",
            "flag-14",
            "flag-15",
            "flag-16",
            "flag-17",
            "flag-18",
            "flag-19",
            "flag-20",
            "flag-21",
            "flag-22",
            "flag-23",
            "flag-24",
            "flag-25",
            "flag-26",
            "flag-27",
            "flag-28",
            "flag-29",
            "flag-30",
            "flag-31",
            "flag-32",
            "flag-33",
            "flag-34",
            "flag-35",
            "flag-36",
            "flag-37",
            "flag-38",
            "flag-39",
            "flag-40",
            "flag-41",
            "flag-42",
            "flag-43",
            "flag-44",
            "flag-45",
            "flag-46",
            "flag-47",
            "flag-48",
            "flag-49",
            "flag-50",
            "flag-51",
            "flag-52",
            "flag-53",
            "flag-54",
            "flag-55",
            "flag-56",
            "flag-57",
            "flag-58",
            "flag-59",
            "flag-60",
            "flag-61",
            "flag-62",
            "flag-63",
            "flag-64",
            "flag-65",
            "flag-66",
            "flag-67",
            "flag-68",
            "flag-69",
            "flag-70",
            "flag-71",
            "flag-72",
            "flag-73",
            "flag-74",
            "flag-75",
            "flag-76",
            "flag-77",
            "flag-78",
            "flag-79",
            "flag-80",
            "flag-81",
            "flag-82",
            "flag-83",
            "flag-84",
            "flag-85",
            "flag-86",
            "flag-87",
            "flag-88",
            "flag-89",
            "flag-90",
            "flag-91",
            "flag-92",
            "flag-93",
            "flag-94",
            "flag-95",
            "flag-96",
            "flag-97",
            "flag-98",
            "flag-99",
            "flag-100",
            "flag-101"
        ],
        "identifier": ""
    }'''

    # Execute Request
    bulk_evaluate_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=bulk_evaluate_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert bulk_evaluate_POST_response.status_code == 400


if __name__ == "__main__":
    test_bulk_evaluate_post()
