# Generated by Skyramp v1.3.21 on 2026-05-04 08:06:47.877323717 +0000 UTC m=+489.666616762
# Command: skyramp generate contract rest http://localhost:8000/api/v1/features/bulk-evaluate/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output bulk_evaluate_contract_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature_names":["my-feature","another-feature"],"identifier":"user-123"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/features/bulk-evaluate/ POST
def test_bulk_evaluate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    bulk_evaluate_POST_request_body = r'''{
        "feature_names": [
            "my-feature",
            "another-feature"
        ],
        "identifier": "user-123"
    }'''

    # Execute Request
    bulk_evaluate_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=bulk_evaluate_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(bulk_evaluate_POST_response, "200")
    assert len(skyramp.get_response_value(bulk_evaluate_POST_response, "results")) == 2
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.0.feature_name") == "my-feature"
    assert isinstance(skyramp.get_response_value(bulk_evaluate_POST_response, "results.0.enabled"), bool)
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.0.reason") in ["DEFAULT", "IDENTITY_OVERRIDE", "UNKNOWN_FLAG"]
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.1.feature_name") == "another-feature"
    assert isinstance(skyramp.get_response_value(bulk_evaluate_POST_response, "results.1.enabled"), bool)
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.1.reason") in ["DEFAULT", "IDENTITY_OVERRIDE", "UNKNOWN_FLAG"]
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.2") is None
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "environment_id") is not None
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "evaluated_at") is not None


if __name__ == "__main__":
    test_bulk_evaluate_post()
