# Generated by Skyramp v1.3.21 on 2026-05-04 08:06:52.500751731 +0000 UTC m=+494.290044786
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output bulk_evaluate_unknown_flags_integration_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_bulk-evaluate-unknown-flags.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "name": "TestOrg2-1746316800"
    }'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/organisations/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "name") == "TestOrg2-1746316800"
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") is not None

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "TestProject2-1746316800",
        "organisation": 1
    }'''

    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_4_POST_response, "name") == "TestProject2-1746316800"
    assert skyramp.get_response_value(endpoint_4_POST_response, "id") is not None

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "TestEnv2-1746316800",
        "project": 1
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/environments/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "TestEnv2-1746316800"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "feature_names": [
            "nonexistent-flag-xyz-1746316800"
        ]
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 200
    assert len(skyramp.get_response_value(endpoint_2_POST_response, "results")) == 1
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.0.feature_name") == "nonexistent-flag-xyz-1746316800"
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.0.enabled") == False
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.0.value") is None
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.0.reason") == "UNKNOWN_FLAG"
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.1") is None
    assert skyramp.get_response_value(endpoint_2_POST_response, "environment_id") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "evaluated_at") is not None


if __name__ == "__main__":
    test_integration()
