# Generated by Skyramp v1.3.19 on 2026-04-20 17:48:22.710926585 +0000 UTC m=+337.115174007
# Command: skyramp generate contract rest http://localhost:8000/api/v1/features/bulk-evaluate/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output bulk_evaluate_security_contract_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature_names":["test-flag"],"identifier":""} \
# 		--response-status-code 403 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/features/bulk-evaluate/ POST
def test_bulk_evaluate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    bulk_evaluate_POST_request_body = r'''{
        "feature_names": [
            "test-flag"
        ],
        "identifier": ""
    }'''

    # Execute Request
    bulk_evaluate_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=bulk_evaluate_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert bulk_evaluate_POST_response.status_code == 403


if __name__ == "__main__":
    test_bulk_evaluate_post()
