# Generated by Skyramp v1.3.21 on 2026-05-18 08:28:52.440717403 +0000 UTC m=+413.175425644
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output bulk_evaluate_known_unknown_flags_integration_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_bulk-evaluate-known-unknown-flags.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    project = "1"

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "name": "TestOrg-1734567890"
    }'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/organisations/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "name") == "TestOrg-1734567890"
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") is not None

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "TestProj-1734567890",
        "organisation": 1
    }'''
    
    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_4_POST_response, "name") == "TestProj-1734567890"
    assert skyramp.get_response_value(endpoint_4_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_4_POST_response, "organisation") == skyramp.get_response_value(endpoint_3_POST_response, "id")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "TestEnv-1734567890",
        "project": 1
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/environments/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"project": project}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "TestEnv-1734567890"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "api_key") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "project") == skyramp.get_response_value(endpoint_4_POST_response, "id")

    # Request Body
    endpoint_5_POST_request_body = r'''{
        "name": "known-flag-1734567890",
        "project": 1
    }'''
    
    # Execute Request
    endpoint_5_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/",
        method="POST",
        body=endpoint_5_POST_request_body,
        headers=headers,
        path_params={"projects": project},
        data_override={"project": project}
    )
    # Generated Assertions
    assert endpoint_5_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_5_POST_response, "name") == "known-flag-1734567890"
    assert skyramp.get_response_value(endpoint_5_POST_response, "id") is not None

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "feature_names": [
            "known-flag-1734567890",
            "no-such-flag-xyz"
        ]
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 200
    assert len(skyramp.get_response_value(endpoint_2_POST_response, "results")) == 2
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.0.feature_name") == "known-flag-1734567890"
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.0.enabled") == False
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.0.value") is None
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.0.reason") == "DEFAULT"
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.1.feature_name") == "no-such-flag-xyz"
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.1.enabled") == False
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.1.value") is None
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.1.reason") == "UNKNOWN_FLAG"
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.2") is None
    assert skyramp.get_response_value(endpoint_2_POST_response, "evaluated_at") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "environment_id") == skyramp.get_response_value(endpoint_1_POST_response, "id")


if __name__ == "__main__":
    test_integration()
