# Generated by Skyramp v1.3.19 on 2026-04-20 17:48:30.957951482 +0000 UTC m=+345.362198914
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output bulk_evaluate_auth_workflow_integration_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_bulk-evaluate-auth-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "email": "admin@example.com",
        "password": "password"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/auth/login/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_POST_response, "token") is not None

    auth_token = skyramp.get_response_value(endpoint_1_POST_response, "token")
    headers["Authorization"] = "Token " + auth_token

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "feature_names": [
            "test-flag",
            "unknown-flag-xyz"
        ],
        "identifier": "user-123"
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.0.feature_name") == "test-flag"
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.0.reason") == "DEFAULT"
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.1.feature_name") == "unknown-flag-xyz"
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.1.reason") == "UNKNOWN_FLAG"
    assert skyramp.get_response_value(endpoint_2_POST_response, "results.2.feature_name") is None
    assert skyramp.get_response_value(endpoint_2_POST_response, "evaluated_at") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "environment_id") is not None


if __name__ == "__main__":
    test_integration()
