# Generated by Skyramp v1.3.21 on 2026-05-04 08:22:02.835613354 +0000 UTC m=+413.867428065
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output feature_audit_happy_path_integration_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_feature-audit-happy-path.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "TestOrg-1714000000"
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/organisations/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "name") == "TestOrg-1714000000"
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None
    org_id = str(skyramp.get_response_value(endpoint_2_POST_response, "id"))

    # Request Body
    endpoint_3_POST_request_body = '{"name": "TestProject-1714000000", "organisation": ' + org_id + '}'

    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "name") == "TestProject-1714000000"
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") is not None
    project_id = str(skyramp.get_response_value(endpoint_3_POST_response, "id"))

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "test-feature-1714000000",
        "type": "STANDARD"
    }'''

    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers,
        path_params={"projects": project_id}
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_4_POST_response, "name") == "test-feature-1714000000"
    assert skyramp.get_response_value(endpoint_4_POST_response, "type") == "STANDARD"
    assert skyramp.get_response_value(endpoint_4_POST_response, "id") is not None
    feature_id = str(skyramp.get_response_value(endpoint_4_POST_response, "id"))

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/{features}/audit/",
        method="GET",
        headers=headers,
        path_params={"features": feature_id}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "feature_name") == "test-feature-1714000000"
    assert skyramp.get_response_value(endpoint_1_GET_response, "feature_id") is not None
    assert skyramp.get_response_value(endpoint_1_GET_response, "total") == 0
    audit_log = skyramp.get_response_value(endpoint_1_GET_response, "audit_log")
    assert len(audit_log) == 0


if __name__ == "__main__":
    test_integration()
