# Generated by Skyramp v1.3.21 on 2026-05-04 08:21:53.555636175 +0000 UTC m=+404.587450865
# Command: skyramp generate contract rest http://localhost:8000/api/v1/features/{pk}/audit/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output feature_audit_security_contract_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--path-params pk=99999 \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/features/{pk}/audit/ GET
def test_audit_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    pk = "99999"

    # Execute Request
    audit_GET_response = client.send_request(
        url=URL,
        path="/api/v1/features/{pk}/audit/",
        method="GET",
        headers=headers,
        path_params={"pk": pk}
    )

    # Generated Assertions
    assert audit_GET_response.status_code == 401
    assert skyramp.get_response_value(audit_GET_response, "detail") == "Authentication credentials were not provided."


if __name__ == "__main__":
    test_audit_get()
