# Generated by Skyramp v1.3.19 on 2026-04-20 18:02:17.789614224 +0000 UTC m=+386.644459216
# Command: skyramp generate contract rest http://localhost:8000/api/v1/features/{pk}/audit/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output feature_audit_security_contract_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--path-params pk=123456 \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/features/{pk}/audit/ GET
def test_audit_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    pk = "123456"

    # Execute Request
    audit_GET_response = client.send_request(
        url=URL,
        path="/api/v1/features/{pk}/audit/",
        method="GET",
        headers=headers,
        path_params={"pk": pk}
    )

    # Generated Assertions
    assert audit_GET_response.status_code == 401


if __name__ == "__main__":
    test_audit_get()
