# Generated by Skyramp v1.3.21 on 2026-05-18 08:41:18.941931747 +0000 UTC m=+311.248224320
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output feature_audit_cross_project_access_integration_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_feature-audit-cross-project-access.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    projects = "1"
    projects_1 = "2"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "SecOrg-1748000000"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/organisations/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "SecOrg-1748000000"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None

    # Request Body
    endpoint_2_POST_request_body = f'{{"name": "ProjectA-1748000000", "organisation": {skyramp.get_response_value(endpoint_1_POST_response, "id")}}}'
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "name") == "ProjectA-1748000000"
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None

    # Request Body
    endpoint_2_POST_1_request_body = f'{{"name": "ProjectB-1748000000", "organisation": {skyramp.get_response_value(endpoint_1_POST_response, "id")}}}'
    
    # Execute Request
    endpoint_2_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_2_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_1_response, "name") == "ProjectB-1748000000"
    assert skyramp.get_response_value(endpoint_2_POST_1_response, "id") is not None

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "name": "cross-proj-flag-1748000000",
        "type": "FLAG"
    }'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers,
        path_params={"projects": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "name") == "cross-proj-flag-1748000000"
    assert skyramp.get_response_value(endpoint_3_POST_response, "type") == "FLAG"
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") is not None

    # Execute Request
    endpoint_4_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/{features}/audit/",
        method="GET",
        headers=headers,
        path_params={
            "features": skyramp.get_response_value(endpoint_3_POST_response, "id"),
            "projects": skyramp.get_response_value(endpoint_2_POST_1_response, "id")
        }
    )
    # Generated Assertions
    assert endpoint_4_GET_response.status_code == 404
    assert skyramp.get_response_value(endpoint_4_GET_response, "detail") == "Not found."


if __name__ == "__main__":
    test_integration()
