# Generated by Skyramp v1.3.21 on 2026-05-18 08:41:10.503313512 +0000 UTC m=+302.809606086
# Command: skyramp generate contract rest http://localhost:8080/api/v1/projects/{project_pk}/features/{pk}/audit/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output feature_audit_not_found_contract_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--path-params project_pk=99999,pk=99999 \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v1/projects/{project_pk}/features/{pk}/audit/ GET
def test_audit_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    pk = "99999"
    project_pk = "99999"

    # Execute Request
    audit_GET_response = client.send_request(
        url=URL,
        path="/api/v1/projects/{project_pk}/features/{pk}/audit/",
        method="GET",
        headers=headers,
        path_params={
            "pk": pk,
            "project_pk": project_pk
        }
    )

    # Generated Assertions
    assert audit_GET_response.status_code == 404
    assert skyramp.get_response_value(audit_GET_response, "detail") == "Not found."


if __name__ == "__main__":
    test_audit_get()
