# Generated by Skyramp v1.3.19 on 2026-04-20 18:02:41.450375074 +0000 UTC m=+410.305220076
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output feature_audit_happy_path_integration_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_feature-audit-happy-path.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    projects = "1"

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "Audit-Test-Org-1745179200"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/organisations/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "name") == "Audit-Test-Org-1745179200"
    org_id = skyramp.get_response_value(endpoint_2_POST_response, "id")

    # Request Body
    endpoint_3_POST_request_body = f'{{"name": "Audit-Test-Proj-1745179200", "organisation": {org_id}}}'
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_3_POST_response, "name") == "Audit-Test-Proj-1745179200"
    project_id = skyramp.get_response_value(endpoint_3_POST_response, "id")

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "audit-flag-1745179200"
    }'''
    
    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers,
        path_params={"projects": project_id}
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_4_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_4_POST_response, "name") == "audit-flag-1745179200"
    feature_id = skyramp.get_response_value(endpoint_4_POST_response, "id")

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/{features}/audit/",
        method="GET",
        headers=headers,
        path_params={"features": feature_id}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "feature_id") == feature_id
    assert skyramp.get_response_value(endpoint_1_GET_response, "feature_name") == "audit-flag-1745179200"
    assert skyramp.get_response_value(endpoint_1_GET_response, "total") == 0
    assert skyramp.get_response_value(endpoint_1_GET_response, "audit_log") is not None


if __name__ == "__main__":
    test_integration()
