# Generated by Skyramp v1.3.16 on 2026-03-30 07:54:20.09676346 +0000 UTC m=+356.327219529
# Command: skyramp generate contract rest http://localhost:8080/api/v1/features/{features}/audit/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_contract_feature_audit_provider.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--path-params features=1 \
# 		--provider \
# 		--response-data {"feature_id":1,"feature_name":"audit_test_flag","audit_log":[],"total":0} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v1/features/{features}/audit/ GET
def test_audit_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    features = "1"

    # Expected Response Body
    expected_audit_GET_response_body = r'''{
        "audit_log": [],
        "feature_id": 1,
        "feature_name": "audit_test_flag",
        "total": 0
    }'''

    # Execute Request
    audit_GET_response = client.send_request(
        url=URL,
        path="/api/v1/features/{features}/audit/",
        method="GET",
        headers=headers,
        path_params={"features": features}
    )

    # Generated Assertions
    assert audit_GET_response.status_code == 200
    assert skyramp.check_schema(audit_GET_response, expected_audit_GET_response_body)
    assert skyramp.get_response_value(audit_GET_response, "audit_log") is not None
    assert skyramp.get_response_value(audit_GET_response, "feature_id") is not None
    assert skyramp.get_response_value(audit_GET_response, "feature_name") is not None
    assert skyramp.get_response_value(audit_GET_response, "total") >= 0


if __name__ == "__main__":
    test_audit_get()
