# Generated by Skyramp v1.3.13 on 2026-03-18 01:38:11.855635439 +0000 UTC m=+311.144499896
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/features/bulk-evaluate/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_fuzz_bulk_evaluate.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature_names":["dark_mode"],"identifier":"user-123"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/v1/features/bulk-evaluate/ POST
def test_bulk_evaluate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    bulk-evaluate_POST_request_body = r'''{
      "feature_names": [
        "dark_mode"
      ],
      "identifier": "user-123"
    }'''
    
    # Fuzz strategies
    bulk_evaluate_post_fuzzed_body = {
        "feature_names": ["0123456789"],
        "identifier": "0123456789"
    }
    # Fuzz status codes
    expected_bulk_evaluate_post_status_code = {
        "feature_names": ["40x"],
        "identifier": "40x"
    }
    # Fuzz status codes for Null values
    expected_bulk_evaluate_post_null_status_code = {
        "feature_names": ["40x"],
        "identifier": "40x"
    }

    # Execute Request
    bulk-evaluate_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=bulk-evaluate_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(bulk_evaluate_post_fuzzed_body):
        # Execute Request
        bulk-evaluate_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/bulk-evaluate/",
            method="POST",
            body=bulk-evaluate_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(bulk_evaluate_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_bulk_evaluate_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(bulk_evaluate_post_fuzzed_body, key) }'
        )

        # Execute Request
        bulk-evaluate_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/bulk-evaluate/",
            method="POST",
            body=bulk-evaluate_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_bulk_evaluate_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_bulk_evaluate_post()
