# Generated by Skyramp v1.3.16 on 2026-03-26 21:35:21.866011899 +0000 UTC m=+242.197722467
# Command: skyramp generate contract rest http://localhost:8080/api/v1/features/bulk-evaluate/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_contract_bulk_evaluate_provider.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature_names":["my-feature-flag","another-flag"],"identifier":"test-user-123"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v1/features/bulk-evaluate/ POST
def test_bulk_evaluate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    bulk_evaluate_POST_request_body = r'''{
        "feature_names": [
            "my-feature-flag",
            "another-flag"
        ],
        "identifier": "test-user-123"
    }'''

    # Execute Request
    bulk_evaluate_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=bulk_evaluate_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(bulk_evaluate_POST_response, "20x")


if __name__ == "__main__":
    test_bulk_evaluate_post()
