# Generated by Skyramp v1.3.13 on 2026-03-18 14:20:58.983360878 +0000 UTC m=+367.729986452
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_bulk_evaluate.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_bulk_evaluate_mixed_flags.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "email": "admin@example.com",
        "password": "TestPass123!"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/auth/login/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "BulkEval Test Org"
    }'''
    
    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/organisations/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201

    # Request Body
    endpoint_5_POST_request_body = r'''{
        "name": "BulkEval Test Project",
        "organisation": 3
    }'''
    
    # Execute Request
    endpoint_5_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_5_POST_request_body,
        headers=headers,
        data_override={"organisation": skyramp.get_response_value(endpoint_4_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_5_POST_response.status_code == 201

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "Development",
        "project": 3
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/environments/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        data_override={"project": skyramp.get_response_value(endpoint_5_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_6_POST_request_body = r'''{
        "description": "Test flag for bulk evaluation",
        "name": "bulk_eval_test_flag",
        "type": "FLAG"
    }'''
    
    # Execute Request
    endpoint_6_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/",
        method="POST",
        body=endpoint_6_POST_request_body,
        headers=headers,
        path_params={"projects": skyramp.get_response_value(endpoint_5_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_6_POST_response.status_code == 201

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "feature_names": [
            "bulk_eval_test_flag",
            "nonexistent_flag_xyz"
        ],
        "identifier": "test-user-001"
    }'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
