# Generated by Skyramp v1.3.13 on 2026-03-18 01:48:01.913820333 +0000 UTC m=+229.509282545
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_feature_audit_trail_integration.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_feature_audit_trail_integration.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "email": "admin@example.com",
        "password": "password"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/auth/login/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "name": "Audit Test Organisation"
    }'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/organisations/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "Audit Test Project",
        "organisation": 1
    }'''
    
    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers,
        data_override={"organisation": skyramp.get_response_value(endpoint_3_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201

    # Request Body
    endpoint_5_POST_request_body = r'''{
        "name": "audit_test_feature",
        "project": 1
    }'''
    
    # Execute Request
    endpoint_5_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/",
        method="POST",
        body=endpoint_5_POST_request_body,
        headers=headers,
        path_params={"projects": skyramp.get_response_value(endpoint_4_POST_response, "id")},
        data_override={"project": skyramp.get_response_value(endpoint_4_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_5_POST_response.status_code == 201

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/{features}/audit/",
        method="GET",
        headers=headers,
        path_params={"features": skyramp.get_response_value(endpoint_5_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
