# Generated by Skyramp v1.3.16 on 2026-03-30 07:56:51.841779846 +0000 UTC m=+508.072235906
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_feature_audit.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_feature_audit_workflow.json

# Import of required libraries
import json
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "AuditTestOrg"
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/organisations/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "name") == "AuditTestOrg"

    # Request Body
    endpoint_3_POST_request_body = json.dumps({
        "name": "AuditTestProject",
        "organisation": skyramp.get_response_value(endpoint_2_POST_response, "id")
    })

    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_3_POST_response, "name") == "AuditTestProject"

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "description": "Feature flag for audit testing",
        "name": "audit_test_flag",
        "type": "STANDARD"
    }'''

    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers,
        path_params={"projects": skyramp.get_response_value(endpoint_3_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_4_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_4_POST_response, "name") == "audit_test_flag"

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/{features}/audit/",
        method="GET",
        headers=headers,
        path_params={"features": skyramp.get_response_value(endpoint_4_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "feature_id") is not None
    assert skyramp.get_response_value(endpoint_1_GET_response, "feature_name") == "audit_test_flag"
    assert skyramp.get_response_value(endpoint_1_GET_response, "total") >= 0


if __name__ == "__main__":
    test_integration()
