# Generated by Skyramp v1.3.16 on 2026-03-30 07:54:37.433803369 +0000 UTC m=+373.664259429
# Command: skyramp generate contract rest http://localhost:8080/api/v1/features/{features}/audit/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_contract_feature_audit_unauth.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--path-params features=1 \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v1/features/{features}/audit/ GET
def test_audit_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    features = "1"

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/features/{features}/audit/",
        method="GET",
        status_code=401
    )
    client.apply_mock(mock)

    # Execute Request
    audit_GET_response = client.send_request(
        url=URL,
        path="/api/v1/features/{features}/audit/",
        method="GET",
        headers=headers,
        path_params={"features": features}
    )

    # Generated Assertions
    assert audit_GET_response.status_code == 401

    client.remove_all_mocks()


if __name__ == "__main__":
    test_audit_get()
