# Generated by Skyramp v1.3.24 on 2026-05-25 08:39:53.017018625 +0000 UTC m=+535.053906382
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output bulk_evaluate_unknown_flag_detection_integration_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/skyramp/scenario_bulk-evaluate-unknown-flag-detection.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "feature_names": [
            "nonexistent_flag_xzy789"
        ]
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200
    assert len(skyramp.get_response_value(endpoint_1_POST_response, "results")) == 1
    assert skyramp.get_response_value(endpoint_1_POST_response, "results.1") is None
    assert skyramp.get_response_value(endpoint_1_POST_response, "results.0.feature_name") == "nonexistent_flag_xzy789"
    assert skyramp.get_response_value(endpoint_1_POST_response, "results.0.enabled") == False
    assert skyramp.get_response_value(endpoint_1_POST_response, "results.0.value") is None
    assert skyramp.get_response_value(endpoint_1_POST_response, "results.0.reason") == "UNKNOWN_FLAG"
    assert skyramp.get_response_value(endpoint_1_POST_response, "evaluated_at") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "environment_id") > 0


if __name__ == "__main__":
    test_integration()
