# Generated by Skyramp v1.3.24 on 2026-05-25 08:39:41.521075478 +0000 UTC m=+523.557963245
# Command: skyramp generate contract rest http://localhost:8080/api/v1/features/bulk-evaluate/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output bulk_evaluate_contract_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature_names":["new_dashboard","beta_features"]} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v1/features/bulk-evaluate/ POST
def test_bulk_evaluate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    bulk_evaluate_POST_request_body = r'''{
        "feature_names": [
            "new_dashboard",
            "beta_features"
        ]
    }'''

    # Execute Request
    bulk_evaluate_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=bulk_evaluate_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(bulk_evaluate_POST_response, "20x")
    assert bulk_evaluate_POST_response.status_code == 200
    assert len(skyramp.get_response_value(bulk_evaluate_POST_response, "results")) == 2
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.2") is None
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.0.feature_name") == "new_dashboard"
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.0.enabled") == False
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.0.value") is None
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.0.reason") == "DEFAULT"
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.1.feature_name") == "beta_features"
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.1.enabled") == False
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.1.value") is None
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.1.reason") == "DEFAULT"
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "evaluated_at") is not None
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "environment_id") > 0


if __name__ == "__main__":
    test_bulk_evaluate_post()
