# Generated by Skyramp v1.3.16 on 2026-03-30 07:36:39.796909052 +0000 UTC m=+240.254184906
# Command: skyramp generate contract rest http://localhost:8080/api/v1/features/bulk-evaluate/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_post_bulk_evaluate_unauth.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/skyramp \
# 		--overwrite \
# 		--request-data {"feature_names":["my-feature-flag"],"identifier":""} \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v1/features/bulk-evaluate/ POST
def test_bulk_evaluate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    bulk_evaluate_POST_request_body = r'''{
        "feature_names": [
            "my-feature-flag"
        ],
        "identifier": ""
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        status_code=401,
        request_body=bulk_evaluate_POST_request_body
    )
    client.apply_mock(mock)

    # Execute Request
    bulk_evaluate_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=bulk_evaluate_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert bulk_evaluate_POST_response.status_code == 401

    client.remove_all_mocks()


if __name__ == "__main__":
    test_bulk_evaluate_post()
