# Generated by Skyramp v1.3.16 on 2026-03-30 07:36:37.077262055 +0000 UTC m=+237.534537859
# Command: skyramp generate contract rest http://localhost:8080/api/v1/features/bulk-evaluate/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_post_bulk_evaluate_provider.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature_names":["my-feature-flag","another-flag"],"identifier":"user-abc-123"} \
# 		--response-data {"results":[{"feature_name":"my-feature-flag","enabled":false,"value":null,"reason":"DEFAULT"},{"feature_name":"another-flag","enabled":false,"value":null,"reason":"DEFAULT"}],"evaluated_at":"2026-03-30T00:00:00Z","environment_id":1} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v1/features/bulk-evaluate/ POST
def test_bulk_evaluate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    bulk_evaluate_POST_request_body = r'''{
        "feature_names": [
            "my-feature-flag",
            "another-flag"
        ],
        "identifier": "user-abc-123"
    }'''

    # Expected Response Body
    expected_bulk_evaluate_POST_response_body = r'''{
        "environment_id": 1,
        "evaluated_at": "2026-03-30T00:00:00Z",
        "results": [
            {
                "enabled": false,
                "feature_name": "my-feature-flag",
                "reason": "DEFAULT",
                "value": null
            },
            {
                "enabled": false,
                "feature_name": "another-flag",
                "reason": "DEFAULT",
                "value": null
            }
        ]
    }'''

    # Execute Request
    bulk_evaluate_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=bulk_evaluate_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert bulk_evaluate_POST_response.status_code == 200
    assert skyramp.check_schema(bulk_evaluate_POST_response, expected_bulk_evaluate_POST_response_body)
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "environment_id") is not None
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "environment_id") >= 1
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "evaluated_at") is not None
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.0.enabled") is not None
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.0.feature_name") == "my-feature-flag"
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.1.feature_name") == "another-flag"
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.0.reason") in ["DEFAULT", "IDENTITY_OVERRIDE", "UNKNOWN_FLAG"]
    assert skyramp.get_response_value(bulk_evaluate_POST_response, "results.1.reason") in ["DEFAULT", "IDENTITY_OVERRIDE", "UNKNOWN_FLAG"]


if __name__ == "__main__":
    test_bulk_evaluate_post()
