# Generated by Skyramp v1.3.16 on 2026-03-30 07:37:22.666972736 +0000 UTC m=+283.124248540
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output integration_post_bulk_evaluate.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/skyramp/scenario_bulk_evaluate_flags_workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "feature_names": [
            "my-feature-flag",
            "another-flag",
            "nonexistent-flag"
        ],
        "identifier": "user-abc-123"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/bulk-evaluate/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_POST_response, "environment_id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "environment_id") >= 1
    assert skyramp.get_response_value(endpoint_1_POST_response, "evaluated_at") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "results.0.feature_name") == "my-feature-flag"
    assert skyramp.get_response_value(endpoint_1_POST_response, "results.0.reason") in ["DEFAULT", "IDENTITY_OVERRIDE", "UNKNOWN_FLAG"]
    assert skyramp.get_response_value(endpoint_1_POST_response, "results.2.feature_name") == "nonexistent-flag"
    assert skyramp.get_response_value(endpoint_1_POST_response, "results.2.reason") == "UNKNOWN_FLAG"


if __name__ == "__main__":
    test_integration()
