# Generated by Skyramp v1.3.24 on 2026-05-25 08:54:42.673420193 +0000 UTC m=+370.043901702
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output feature_audit_create_and_read_integration_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests/skyramp/api \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/skyramp/api/scenario_feature-audit-create-and-read.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Use timestamp suffix to avoid collisions across test runs
    ts = int(time.time())

    # Request Body
    endpoint_2_POST_request_body = '{{"name": "AuditTestOrg-{ts}"}}'.format(ts=ts)

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/organisations/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "name") == "AuditTestOrg-{}".format(ts)
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") > 0
    org_id = skyramp.get_response_value(endpoint_2_POST_response, "id")

    # Request Body
    endpoint_3_POST_request_body = '{{"name": "AuditTestProject-{ts}", "organisation": {org_id}}}'.format(ts=ts, org_id=org_id)

    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "name") == "AuditTestProject-{}".format(ts)
    assert skyramp.get_response_value(endpoint_3_POST_response, "organisation") == org_id
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") > 0
    project_id = skyramp.get_response_value(endpoint_3_POST_response, "id")

    # Request Body
    endpoint_4_POST_request_body = '{{"name": "audit-feature-{ts}", "type": "FLAG"}}'.format(ts=ts)

    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{project_id}/features/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers,
        path_params={"project_id": str(project_id)}
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_4_POST_response, "name") == "audit-feature-{}".format(ts)
    assert skyramp.get_response_value(endpoint_4_POST_response, "type") == "FLAG"
    assert skyramp.get_response_value(endpoint_4_POST_response, "id") > 0
    feature_id = skyramp.get_response_value(endpoint_4_POST_response, "id")

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/{pk}/audit/",
        method="GET",
        headers=headers,
        path_params={"pk": str(feature_id)}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "feature_id") == feature_id
    assert skyramp.get_response_value(endpoint_1_GET_response, "feature_name") == "audit-feature-{}".format(ts)
    assert len(skyramp.get_response_value(endpoint_1_GET_response, "audit_log")) == 0
    assert skyramp.get_response_value(endpoint_1_GET_response, "total") == 0
    assert skyramp.get_response_value(endpoint_1_GET_response, "total") == len(skyramp.get_response_value(endpoint_1_GET_response, "audit_log"))


if __name__ == "__main__":
    test_integration()
