# Generated by Skyramp v1.3.24 on 2026-05-25 08:54:33.678856909 +0000 UTC m=+361.049338418
# Command: skyramp generate contract rest http://localhost:8080/api/v1/features/{pk}/audit/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests/skyramp/api \
# 		--overwrite \
# 		--path-params pk=99999 \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# security boundary test: unauthenticated access returns 401
def test_audit_get_unauthenticated():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # No auth headers — verifies endpoint requires authentication
    headers = {}

    # Declaration of variables
    pk = "99999"

    # Execute Request
    audit_GET_unauth_response = client.send_request(
        url=URL,
        path="/api/v1/features/{pk}/audit/",
        method="GET",
        headers=headers,
        path_params={"pk": pk}
    )

    # Generated Assertions
    assert audit_GET_unauth_response.status_code == 401
    assert skyramp.get_response_value(audit_GET_unauth_response, "detail") == "Authentication credentials were not provided."


# error handling test: non-existent feature returns 404 (will fail with 500 due to routing bug)
def test_audit_get_not_found():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    pk = "99999"

    # Execute Request
    audit_GET_response = client.send_request(
        url=URL,
        path="/api/v1/features/{pk}/audit/",
        method="GET",
        headers=headers,
        path_params={"pk": pk}
    )

    # Generated Assertions
    assert audit_GET_response.status_code == 404
    assert skyramp.get_response_value(audit_GET_response, "detail") == "Not found."


if __name__ == "__main__":
    test_audit_get_unauthenticated()
    test_audit_get_not_found()
